resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- metrics_auth_role.yaml
- metrics_auth_role_binding.yaml
- metrics_reader_role.yaml
- namespaceclass_admin_role.yaml
- namespaceclass_editor_role.yaml
- namespaceclass_viewer_role.yaml
