apiVersion: namespaceclass.akuity.io/v1alpha1
kind: NamespaceClass
metadata:
  name: internal-network
spec:
  resources:
    # 10.8.0.0/16 is an example range for the corporate VPN.
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: ingress
      spec:
        podSelector: {}
        policyTypes:
          - Ingress
        ingress:
          - from:
              - ipBlock:
                  cidr: 10.8.0.0/16
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: egress
      spec:
        podSelector: {}
        policyTypes:
          - Egress
        egress:
          - to:
              - ipBlock:
                  cidr: 10.8.0.0/16
          - to:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: kube-system
                podSelector:
                  matchLabels:
                    k8s-app: kube-dns
            ports:
              - protocol: UDP
                port: 53
              - protocol: TCP
                port: 53
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: network-info
      data:
        vpnCIDR: 10.8.0.0/16
